### ISSUE TITLE
Lab starter files

### ISSUE THREAD

**Issue by cyugao** [dstodolny/cs61c#1]
Hi, sorry to bother you. I am just wondering where you found those starter files. They don't seem to be available on the course site.

**Comment by cyugao** [comment]
Oh, I found them in the 2020 version. You can delete this issue now.

**Comment by dstodolny** [comment]
They're also here https://github.com/cs61c-spring2015

**Comment by cyugao** [comment]
Thanks. Yes, I found that one but there are no labs.
